export const registerInputs = [
  {
    name: 'firstname',
    type: 'text',
    label: 'Nombres',
    placeholder: 'Ingrese sus nombres...',
    required: true,
    validFeedback: '',
    invalidFeedback: 'Los nombres son obligatorios. Máximo 50 caracteres',
    maxLength: 50,
    minLength: 1,
  },
  {
    name: 'lastname',
    type: 'text',
    label: 'Apellidos',
    placeholder: 'Ingrese sus apellidos...',
    required: true,
    validFeedback: '',
    invalidFeedback: 'Los apellidos son obligatorios. Máximo 50 caracteres',
    maxLength: 50,
    minLength: 1,
  },
  {
    name: 'email',
    type: 'email',
    label: 'Correo',
    placeholder: 'Ingrese su correo...',
    required: true,
    validFeedback: '',
    invalidFeedback: 'El correo es obligatorio y debe poseer el formato de email. Máximo 50 caracteres',
    maxLength: 50,
    minLength: 1,
  },
  {
    name: 'password',
    type: 'password',
    label: 'Contraseña',
    placeholder: 'Ingrese su contraseña...',
    required: true,
    validFeedback: '',
    invalidFeedback: 'La contraseña es obligatoria. De 8 a 30 caracteres',
    maxLength: 30,
    minLength: 8,
  },
  {
    name: 'c-password',
    type: 'password',
    label: 'Confirmar contraseña',
    placeholder: 'Vuelva a ingresar su contraseña...',
    required: true,
    validFeedback: '',
    invalidFeedback: '',
    maxLength: 30,
    minLength: 8,
  },
];

export const loginInputs = [
  {
    name: 'email',
    type: 'email',
    label: 'Correo',
    placeholder: 'Ingrese su correo...',
    required: true,
    validFeedback: '',
    invalidFeedback: 'El correo es obligatorio y debe poseer el formato de email. Máximo 50 caracteres',
    maxLength: 50,
    minLength: 1,
  },
  {
    name: 'password',
    type: 'password',
    label: 'Contraseña',
    placeholder: 'Ingrese su contraseña...',
    required: true,
    validFeedback: '',
    invalidFeedback: 'La contraseña es obligatoria. De 8 a 30 caracteres',
    maxLength: 30,
    minLength: 8,
  },
];
